import {AssetsItem} from './AssetsTableItem.types';
import iconsObj from 'assets/icons/iconsObj';

const menuItems: AssetsItem[] = [
  {
    title: 'divider',
    isDivider: true,
  },
  {
    title: 'usdt',
    secondaryTitle: 'usdtSecondary',
    percent: 49,
    valueIsMinus: false,
    priceTitle: 1,
    secondaryPricePercentTitle: 15.32,
    valueTitle: 8310072.32,
    pricePercentDollar: 163.63,
    valueSecondaryTitle: 8310072.32,
    icon: iconsObj.assetsUsdt,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 48939.13,
    title: 'btc',
    valueTitle: 1150066.5,
    valueSecondaryTitle: 8310072.32,
    valueIsMinus: false,
    pricePercentDollar: 163.63,
    secondaryPricePercentTitle: 15.32,
    secondaryTitle: 'btcSecondary',
    percent: 24,
    icon: iconsObj.assetsBitcoin,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 4303.0,
    title: 'eth',
    secondaryTitle: 'ethSecondary',
    valueTitle: 1150066.5,
    valueSecondaryTitle: 8310072.32,
    valueIsMinus: true,
    pricePercentDollar: 163.63,
    secondaryPricePercentTitle: 15.32,
    percent: 23,
    icon: iconsObj.assetsEth,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 28,
    title: 'ufo',
    secondaryTitle: 'ufoSecondary',
    secondaryPricePercentTitle: 15.32,
    valueIsMinus: false,
    valueTitle: 1072.32,
    valueSecondaryTitle: 8310072.32,
    pricePercentDollar: 163.63,
    percent: 2,
    icon: iconsObj.assetsUfo,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 29.53,
    title: 'gel',
    secondaryTitle: 'gelSecondary',
    secondaryPricePercentTitle: 15.32,
    valueIsMinus: false,
    valueTitle: 1072.32,
    valueSecondaryTitle: 8310072.32,
    pricePercentDollar: 163.63,
    percent: 1,
    icon: iconsObj.assetsGel,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 11.45,
    title: 'cqt',
    secondaryTitle: 'cqtSecondary',
    percent: 1,
    secondaryPricePercentTitle: 15.32,
    valueTitle: 1072.32,
    valueSecondaryTitle: 8310072.32,
    valueIsMinus: true,
    pricePercentDollar: 163.63,
    icon: iconsObj.assetsCqt,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 53.89,
    title: 'ftm',
    secondaryTitle: 'ftmSecondary',
    percent: 1,
    valueTitle: 1072.32,
    valueSecondaryTitle: 8310072.32,
    secondaryPricePercentTitle: 15.32,
    valueIsMinus: false,
    pricePercentDollar: 163.63,
    icon: iconsObj.assetsFtm,
  },
  {
    title: 'divider',
    isDivider: true,
  },
  {
    priceTitle: 73.89,
    title: 'matic',
    secondaryTitle: 'maticSecondary',
    valueIsMinus: false,
    valueTitle: 1072.32,
    valueSecondaryTitle: 8310072.32,
    pricePercentDollar: 163.63,
    secondaryPricePercentTitle: 15.32,
    percent: 1,
    icon: iconsObj.assetsMatic,
  },
];

export {menuItems};
